web:
  upload-path: E://projectFile/wxappShop
#  upload-path: /file/qiandaohu

server:
  port: 8888
  servlet:
    context-path: /appserver


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wxapp_shop?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  resources:
    static-locations: file:${web.upload-path}
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 50MB

logging:
#  path: /log/qiandaohu
  path: E://proectLog/wxappShop
  level:
    lombok.core.debug: debug

mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: cn.yfkj.entity
